version: '3'
services:
  node:
    restart: always
    image: sovichetra/docker-assignment
    ports:
      - 8400:3000
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
